/* CISC 1610: - Computer Science I Lab
 * 
 * Lab 6 - Random Number Game
 *
 * This program makes a random number guessing game for users, utilizing seeds and programmer-defined functions.
 *
 * Jack Forester 
 * Last Edited: October 17, 2023
 *
 *
 */

#include <iostream>
#include <cstdlib>
using namespace std;
bool runGame ();
// Runs a game in which the user has three tries to guess a random number generated by the computer. Returns true if the// user wins, false if the user loses.


int main() {

    srand(10);
    int numWins = 0;
    int numLosses = 0;
    char play;
    
    cout << "Can you guess the number I generated within three tries?\n";
    
    do { 
        bool result = runGame();
        if (result) {
            numWins++;
        }
        else {
            numLosses++;
        }

        cout << "Would you like to play again? (Y/N): ";
        cin >> play;
        
        if (play == 'Y' || play == 'y') {
		cout << "Can you guess the number I generated within three tries?\n";
	}

        while (play != 'Y' && play != 'y' && play != 'N' && play != 'n') {
            cout << "Please enter a valid response. (Y/N): ";
            cin >> play;
        }
    } while (play == 'Y' || play == 'y'); 
    
    cout << "Number of wins: " << numWins << endl                   
         << "Number of losses: " << numLosses << endl
         << "Thanks for playing!";
         return 0;
}

bool runGame() {
        
        int guess;
        int numGuesses = 3;
        int num = rand() % 10 + 1;

        while (numGuesses > 0) {
                cout << "Guess a number between one and ten: ";
                cin >> guess;
                if (guess == num) {
                        cout << "You win!\n";
                        numGuesses = 0;
                        return true;
                }
                else if (guess < num) {
                        cout << "Go higher.\n";
                        numGuesses--;
                        cout << "You have " << numGuesses << " guess(es) left.\n";
                }
                else if (guess > num) {
                        cout << "Go lower.\n";
                        numGuesses--;
                        cout << "You have " << numGuesses << " guess(es) left.\n";
                }
        } 
        
        return (false);          
}

